######################################################################
##
## Filename: Usr_interaction_tb.udo
## Created on: Sun Mar 18 1:16:51 PM Eastern Daylight Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
