######################################################################
##
## Filename: vending_machine_controller_tb.udo
## Created on: Wed Mar 21 7:21:46 PM Eastern Daylight Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
